[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "complex-calculated-coffee.html"
url = "/complex-calculated-coffee.html"
title = "Complex, Calculated Coffee!"

[[input.files]]
path = "jupyter-lab-setup-for-electrical-engineers.html"
url = "/jupyter-lab-setup-for-electrical-engineers.html"
title = "Jupyter Lab Setup for Electrical Engineers"

[[input.files]]
path = "a-collaborative-wordcloud-for-teaching.html"
url = "/a-collaborative-wordcloud-for-teaching.html"
title = "A Collaborative Word Cloud for Teaching"

[[input.files]]
path = "basic-auth-without-the-hubub-in-nginx.html"
url = "/basic-auth-without-the-hubub-in-nginx.html"
title = "Basic Auth without the Hubub in NGINX"

[[input.files]]
path = "making-portable-digital-learning.html"
url = "/making-portable-digital-learning.html"
title = "Making Portable Digital Learning"

[[input.files]]
path = "presenting-at-linux-fest-northwest-2024.html"
url = "/presenting-at-linux-fest-northwest-2024.html"
title = "I'm Presenting at LinuxFest Northwest 2024!"

[[input.files]]
path = "first-time-as-a-guest-lecturer.html"
url = "/first-time-as-a-guest-lecturer.html"
title = "First Time as a Guest Lecturer?"

[[input.files]]
path = "electronics-dissection-amping-up.html"
url = "/electronics-dissection-amping-up.html"
title = "Electronics Dissection - Amping Up"

[[input.files]]
path = "tx-rx-swapping-made-ez.html"
url = "/tx-rx-swapping-made-ez.html"
title = "TX/RX Swapping Made EZ"

[[input.files]]
path = "the-4-h-lineup-for-spring-2024.html"
url = "/the-4-h-lineup-for-spring-2024.html"
title = "The 4-H Lineup (for Spring, 2024)"

[[input.files]]
path = "quick-n-simple-photo-converter.html"
url = "/quick-n-simple-photo-converter.html"
title = "Quick-n-Simple Photo Converter (for HEIC format)"

[[input.files]]
path = "adding-a-subscription-system-to-my-blog.html"
url = "/adding-a-subscription-system-to-my-blog.html"
title = "Adding a Subscription System to my Blog"

[[input.files]]
path = "adding-search-to-my-pelican-blog-site.html"
url = "/adding-search-to-my-pelican-blog-site.html"
title = "Adding Search to my Pelican Blog Site"

[[input.files]]
path = "how-many-protocols-does-it-take-to-open-a-door.html"
url = "/how-many-protocols-does-it-take-to-open-a-door.html"
title = "How Many Protocols Does it Take to Open a Door?"

[[input.files]]
path = "custom-lightning-on-demand.html"
url = "/custom-lightning-on-demand.html"
title = "Custom Lightning on Demand"

[[input.files]]
path = "dissecting-computers-for-the-first-time.html"
url = "/dissecting-computers-for-the-first-time.html"
title = "Dissecting Computers for the First Time?"

[[input.files]]
path = "kyg-2023.html"
url = "/kyg-2023.html"
title = "KYG 2023"

[[input.files]]
path = "updated-wiki-page-for-capstone-projects.html"
url = "/updated-wiki-page-for-capstone-projects.html"
title = "Updated Wiki Page for Capstone Projects"

[[input.files]]
path = "making-configuration-for-a-python-application-simple.html"
url = "/making-configuration-for-a-python-application-simple.html"
title = "Making Configuration for a Python Application Simple!"

[[input.files]]
path = "packaging-single-file-python-projects.html"
url = "/packaging-single-file-python-projects.html"
title = "Packaging Single File Python Projects"

[[input.files]]
path = "python-pianobar-and-mqtt.html"
url = "/python-pianobar-and-mqtt.html"
title = "Python, Pianobar, and MQTT?"

[[input.files]]
path = "using-pipewire-link-to-bridge-the-gaps.html"
url = "/using-pipewire-link-to-bridge-the-gaps.html"
title = "Using Pipewire Link to Bridge the Gaps"

[[input.files]]
path = "the-ranch-gets-a-face-lift.html"
url = "/the-ranch-gets-a-face-lift.html"
title = "The Ranch (KRNC) Gets a Face Lift"

[[input.files]]
path = "giving-up-on-low-level-linux-audio.html"
url = "/giving-up-on-low-level-linux-audio.html"
title = "I'm Giving Up on Low-Level Audio in Linux"

[[input.files]]
path = "adding-radon-sensors-to-homeassistant.html"
url = "/adding-radon-sensors-to-homeassistant.html"
title = "Adding Radon Sensors to Home Assistant"

[[input.files]]
path = "installing-vban-on-linux-with-pipewire.html"
url = "/installing-vban-on-linux-with-pipewire.html"
title = "Installing VBAN on Linux Systems with Pipewire"

[[input.files]]
path = "reverse-proxying-to-two-git-servers.html"
url = "/reverse-proxying-to-two-git-servers.html"
title = "Reverse Proxying to two Git Servers"

[[input.files]]
path = "my-way-of-installing-python-on-windows-in-2022.html"
url = "/my-way-of-installing-python-on-windows-in-2022.html"
title = "My Way of Intalling Python on Windows in 2022"

[[input.files]]
path = "spooky-scary-porch-projects.html"
url = "/spooky-scary-porch-projects.html"
title = "Spooky Scary Porch Projects"

[[input.files]]
path = "starting-jenkins-right-away-in-winders.html"
url = "/starting-jenkins-right-away-in-winders.html"
title = "Starting Jenkins Right Away in Winders"

[[input.files]]
path = "finding-broken-blog-links.html"
url = "/finding-broken-blog-links.html"
title = "Finding Broken Blog Links"

[[input.files]]
path = "mt-st-helens-adventures.html"
url = "/mt-st-helens-adventures.html"
title = "Mount St. Helens Adventures"

[[input.files]]
path = "making-drawing-circuits-in-markdown-a-cinch.html"
url = "/making-drawing-circuits-in-markdown-a-cinch.html"
title = "Making Drawing Circuits in Markdown a Cinch!"

[[input.files]]
path = "scraping-the-isp-router-to-support-selfhosting.html"
url = "/scraping-the-isp-router-to-support-selfhosting.html"
title = "Scraping the ISP Router to Support Self-Hosting"

[[input.files]]
path = "rheo-railroad-a-digital-toy-train.html"
url = "/rheo-railroad-a-digital-toy-train.html"
title = "RheoRailroad - A Digital Toy Train Set"

[[input.files]]
path = "making-feline-stink-a-distant-memory.html"
url = "/making-feline-stink-a-distant-memory.html"
title = "Making Feline Stink a Distant Memory"

[[input.files]]
path = "photos-in-the-nick-of-time-at-stac.html"
url = "/photos-in-the-nick-of-time-at-stac.html"
title = "Photos in the Nick of Time at STAC"

[[input.files]]
path = "making-progress-with-capstones.html"
url = "/making-progress-with-capstones.html"
title = "Making Progress with Capstones"

[[input.files]]
path = "home-automation-condensed.html"
url = "/home-automation-condensed.html"
title = "Home Automation... Condensed!"

[[input.files]]
path = "more-servers-in-the-basement.html"
url = "/more-servers-in-the-basement.html"
title = "More Servers in the Basement?"

[[input.files]]
path = "error-pages-for-education.html"
url = "/error-pages-for-education.html"
title = "Error Pages for Education"

[[input.files]]
path = "what-is-tasmota-anyway.html"
url = "/what-is-tasmota-anyway.html"
title = "What is Tasmota, Anyway?"

[[input.files]]
path = "automagic-test-websites.html"
url = "/automagic-test-websites.html"
title = "Automagic Test Websites"

[[input.files]]
path = "ideas-for-swine-education.html"
url = "/ideas-for-swine-education.html"
title = "Ideas for Swine Education"

[[input.files]]
path = "bringing-light-to-the-living-room.html"
url = "/bringing-light-to-the-living-room.html"
title = "Bringing Light to the... Living Room?"

[[input.files]]
path = "sensing-fire-in-a-world-without-water.html"
url = "/sensing-fire-in-a-world-without-water.html"
title = "Sensing Fire in a World Without Water"

[[input.files]]
path = "using-python-to-provide-simple-photo-connections-for-youth.html"
url = "/using-python-to-provide-simple-photo-connections-for-youth.html"
title = "Using Python to Provide Simple Photo Connections for Youth"

[[input.files]]
path = "adding-plantuml-to-pelican-without-installing-java.html"
url = "/adding-plantuml-to-pelican-without-installing-java.html"
title = "Adding PlantUML to Pelican Without Installing Java?"

[[input.files]]
path = "think-you-know-everything.html"
url = "/think-you-know-everything.html"
title = "Think you Know Everything?"

[[input.files]]
path = "reactjs-python-pictures-and-4h.html"
url = "/reactjs-python-pictures-and-4h.html"
title = "React.js, Python, Pictures, and 4-H!"

[[input.files]]
path = "telnetlib-python-and-sel-protocol.html"
url = "/telnetlib-python-and-sel-protocol.html"
title = "Telnetlib, Python, and SEL Protocol"

[[input.files]]
path = "a-different-way-to-wrap-gifts.html"
url = "/a-different-way-to-wrap-gifts.html"
title = "A \\\"Different\\\" Way to Wrap Gifts"

[[input.files]]
path = "creepy-killer-vibes.html"
url = "/creepy-killer-vibes.html"
title = "Creepy, Killer Vibes?"

[[input.files]]
path = "finding-fire-and-making-it.html"
url = "/finding-fire-and-making-it.html"
title = "Finding Fire and Making It"

[[input.files]]
path = "automating-python-releases-with-github-actions.html"
url = "/automating-python-releases-with-github-actions.html"
title = "Automating Python Releases with GitHub Actions"

[[input.files]]
path = "dj-joe-playlister.html"
url = "/dj-joe-playlister.html"
title = "DJ Joe Playlister"

[[input.files]]
path = "why-do-i-selfhost.html"
url = "/why-do-i-selfhost.html"
title = "Why do I Self-Host?"

[[input.files]]
path = "just-some-thoghts-on-a-song.html"
url = "/just-some-thoghts-on-a-song.html"
title = "Just Some Thoghts on a Song"

[[input.files]]
path = "a-better-way-to-integrate-with-voicemeeter.html"
url = "/a-better-way-to-integrate-with-voicemeeter.html"
title = "A Better Way to Integrate with VoiceMeeter?"

[[input.files]]
path = "tech-podcasts-galore.html"
url = "/tech-podcasts-galore.html"
title = "Tech Podcasts Galore!"

[[input.files]]
path = "hearing-fires-while-seeing-smoke.html"
url = "/hearing-fires-while-seeing-smoke.html"
title = "Hearing Fires While Seeing Smoke"

[[input.files]]
path = "demonstrating-electricity.html"
url = "/demonstrating-electricity.html"
title = "Demonstrating Electricity"

[[input.files]]
path = "powering-my-own-relaxation.html"
url = "/powering-my-own-relaxation.html"
title = "Powering My Own Relaxation"

[[input.files]]
path = "spam-the-vban-for-non-stop-audio.html"
url = "/spam-the-vban-for-non-stop-audio.html"
title = "Spam the VBAN for Non-Stop Audio"

[[input.files]]
path = "jenkins-servers-in-the-basement.html"
url = "/jenkins-servers-in-the-basement.html"
title = "Servers in the Basement..."

[[input.files]]
path = "jenkins-on-sel-industrial-hardware.html"
url = "/jenkins-on-sel-industrial-hardware.html"
title = "CI/CD On Industrial Grade Hardware"

[[input.files]]
path = "gitlab-jenkins-and-the-rpi.html"
url = "/gitlab-jenkins-and-the-rpi.html"
title = "GitLab, Jenkins, Python, and the Raspberry Pi!"

[[input.files]]
path = "networked-audio-using-vban-and-rpi.html"
url = "/networked-audio-using-vban-and-rpi.html"
title = "Synchronizing Home Audio with the Raspberry Pi and VBAN"

[[input.files]]
path = "pycev-a-python-cev-reader.html"
url = "/pycev-a-python-cev-reader.html"
title = "pycev - A Python CEV Reader"

[[input.files]]
path = "sustainability-in-the-news-december-2020.html"
url = "/sustainability-in-the-news-december-2020.html"
title = "Sustainability in the News..."

[[input.files]]
path = "esp32-controlling-lionel-trains.html"
url = "/esp32-controlling-lionel-trains.html"
title = "Smart Christmas Trains for a Smart Home?"

[[input.files]]
path = "reading-data-with-selprotopy.html"
url = "/reading-data-with-selprotopy.html"
title = "Reading Data with selprotopy"

[[input.files]]
path = "sel-protocol-coming-to-python.html"
url = "/sel-protocol-coming-to-python.html"
title = "Introducing selprotopy"

[[input.files]]
path = "write-framework-once.html"
url = "/write-framework-once.html"
title = "Write a Good Framework - ONCE."

[[input.files]]
path = "detecting-fires-with-sound.html"
url = "/detecting-fires-with-sound.html"
title = "Wildfire Prevention with Sound"

[[input.files]]
path = "iec-61131-syntax-highlighting.html"
url = "/iec-61131-syntax-highlighting.html"
title = "IEC 61131-3 Syntax Highlighting with highlight.js"

[[input.files]]
path = "making-bitmap-images-from-bytes.html"
url = "/making-bitmap-images-from-bytes.html"
title = "A Picture is Worth a Thousand Words"

[[input.files]]
path = "we're-going-live.html"
url = "/we're-going-live.html"
title = "We're going live."
