name: Broken Link Detector
on:
  schedule:
    # Runs every day at 1:00AM
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  find-broken-links:
    name: Find Broken Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade lxml beautifulsoup4 requests
    - name: Find Broken Links
      run: |
        python broken-link-detector.py