# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Pelican-WebBuilder
on:
  push:
    branches:
      - master

jobs:
  build-and-delpoy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04
          chmod +x stork-ubuntu-20-04
          echo $(pwd) >> $GITHUB_PATH
          echo $(pwd)
          echo $GITHUB_PATH
          pip install -r requirements.txt
      - name: Build Pelican Pages
        if: success()
        run: |
          pelican -s pelicanconf.py --fatal errors

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/
          cname: blog.stanleysolutionsnw.com
