# Syntax reference for this file:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Pelican-WebBuilder
on:
  push:
    branches:
      - master

jobs:
  build-and-delpoy:
    name: Pelican-Generate-HTML
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04 -O stork
          chmod +x stork
          echo $(pwd) >> $GITHUB_PATH
          pip install -r requirements.txt
      - name: Build Pelican Pages
        if: success()
        run: |
          echo "Working Directory: ${PATH}"
          pelican -s pelicanconf.py --fatal errors

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/
          cname: blog.stanleysolutionsnw.com
